### ISSUE TITLE
Once I apply the KC module, it get very slow....

### ISSUE THREAD

**Issue by linhaojia13** [YiruS/KCNet#1]
The KC kernel contains only 16*16*3=768 parameters, however the program got stuck in the backward propagation even on P100 with batchsize 1.  Why? What can I do to solve it?
Thanks a lot!

**Comment by hujunsheng** [comment]
可以加我微信交流一下吗h1031656485

**Comment by hujunsheng** [comment]
> The KC kernel contains only 16_16_3=768 parameters, however the program got stuck in the backward propagation even on P100 with batchsize 1. Why? What can I do to solve it?
> Thanks a lot!

可以加我微信交流一下吗

**Comment by YiruS** [comment]
Sorry for the late response. The original KCNet was implemented using Caffe and the current PyTorch version is not tested.

**Comment by linhaojia13** [comment]
Thank you anyway. @YiruS
